# for web
server:
  port: 8080

# for spring
spring:
  # config:
  #   activate:
  #     on-profile: test
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    generate-ddl: off
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: SA
    password:
    initialization-mode: always
    schema: classpath:schema-h2.sql
    data: classpath:data-h2.sql

  mvc:
    view:
      prefix: /myApp/
      suffix: .jsp

  thymeleaef:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

# for SLF4J
logging:
  file:
    name: ${user.dir}/log/test.log  # Log file path
    max-history: 7 # delete period
    max-size: 10MB  # max size of single log file
  level:  # set log level to each package
    com.aswinblue.RankServer : debug
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"